version: "3.7"

services:
  php:
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/etc/php/7.2/apache2/php.ini
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8006:80
    environment:
      - UPLOAD_LIMIT=1G
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
